all: padd2 add2

add2: add2.o 
	gcc -Wall -g $^ -o $@

add2.o: add2.c 
	gcc -Wall -g -c $< -o $@

padd2: padd2.o 
	gcc -Wall -g $^ -o $@

padd2.o: padd2.c 
	gcc -Wall -g -c $< -o $@

clean: 
	@echo "start clean..."
	-rm -f *.o core.* *.log *~ *.swp padd2 add2
	@echo "end clean"

.PHONY: clean
