all: padd2

padd2: padd2.o 
	gcc -Wall -g $^ -o $@

padd2.o: padd2.c 
	gcc -Wall -g -c $< -o $@

clean: 
	@echo "start clean..."
	-rm -f *.o core.* *.log *~ *.swp padd2 
	@echo "end clean"

.PHONY: clean
