all: icanput ilist igetmsg

igetmsg: igetmsg.o 
	gcc -Wall -g $^ -o $@

igetmsg.o: igetmsg.c 
	gcc -Wall -g -c $< -o $@

ilist: ilist.o 
	gcc -Wall -g $^ -o $@

ilist.o: ilist.c 
	gcc -Wall -g -c $< -o $@

icanput: icanput.o 
	gcc -Wall -g $^ -o $@

icanput.o: icanput.c 
	gcc -Wall -g -c $< -o $@

clean: 
	@echo "start clean..."
	-rm -f *.o core.* *.log *~ *.swp icanput ilist igetmsg
	@echo "end clean"

.PHONY: clean
