all: pty slowout

slowout: slowout.c 
	gcc -Wall -g $^ -o $@

pty: pty.o tty.o pty_fun.o
	gcc -Wall -g $^ -o $@

pty.o: pty.c ../tty.h ../pty_fun.h
	gcc -Wall -g -c $< -o $@

tty.o: ../tty.c ../tty.h 
	gcc -Wall -g -c $< -o $@

pty_fun.o: ../pty_fun.c ../pty_fun.h 
	gcc -Wall -g -c $< -o $@ 

clean: 
	@echo "start clean..."
	-rm -f *.o core.* *.log *~ *.swp pty slowout
	@echo "end clean"

.PHONY: clean
